#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x12A53B890119D176 (omer.drow@gmail.com)
#
Name     : amqp
Version  : 2.3.2
Release  : 39
URL      : http://pypi.debian.net/amqp/amqp-2.3.2.tar.gz
Source0  : http://pypi.debian.net/amqp/amqp-2.3.2.tar.gz
Source99 : http://pypi.debian.net/amqp/amqp-2.3.2.tar.gz.asc
Summary  : Low-level AMQP client for Python (fork of amqplib).
Group    : Development/Tools
License  : BSD-3-Clause-Clear
Requires: amqp-python3
Requires: amqp-license
Requires: amqp-python
Requires: vine
BuildRequires : amqp
BuildRequires : buildreq-distutils3
BuildRequires : coverage
BuildRequires : linecache2
BuildRequires : nose
BuildRequires : nose-cover3
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-mock
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : six
BuildRequires : traceback2
BuildRequires : unittest2
BuildRequires : vine

%description
Python AMQP 0.9.1 client library
        =====================================================================
        
        |build-status| |coverage| |license| |wheel| |pyversion| |pyimp|

%package license
Summary: license components for the amqp package.
Group: Default

%description license
license components for the amqp package.


%package python
Summary: python components for the amqp package.
Group: Default
Requires: amqp-python3

%description python
python components for the amqp package.


%package python3
Summary: python3 components for the amqp package.
Group: Default
Requires: python3-core

%description python3
python3 components for the amqp package.


%prep
%setup -q -n amqp-2.3.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532213595
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
py.test-2.7 -v funtests/ || :
%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/amqp
cp LICENSE %{buildroot}/usr/share/doc/amqp/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/amqp/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
