#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : amqp
Version  : 2.2.1
Release  : 35
URL      : http://pypi.debian.net/amqp/amqp-2.2.1.tar.gz
Source0  : http://pypi.debian.net/amqp/amqp-2.2.1.tar.gz
Summary  : Low-level AMQP client for Python (fork of amqplib).
Group    : Development/Tools
License  : BSD-3-Clause-Clear
Requires: amqp-python
Requires: vine
BuildRequires : amqp
BuildRequires : coverage
BuildRequires : linecache2
BuildRequires : nose
BuildRequires : nose-cover3
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python-mock
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : six
BuildRequires : traceback2
BuildRequires : unittest2
BuildRequires : vine

%description
Python AMQP 0.9.1 client library
        =====================================================================
        
        |build-status| |coverage| |license| |wheel| |pyversion| |pyimp|

%package python
Summary: python components for the amqp package.
Group: Default

%description python
python components for the amqp package.


%prep
%setup -q -n amqp-2.2.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1500022664
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
py.test-2.7 -v funtests/ || :
%install
export SOURCE_DATE_EPOCH=1500022664
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
